### PR TITLE
Support ubuntu 20.04 and ros noetic

### PR DESCRIPTION
**Pull request by JS00000**
Add a CMakeLists file to support ubuntu 20.04 and ros noetic.

### CODE REVIEW

**Comment by lianghongzhuo** [comment]
I think there is no need to add a new file for ubuntu 20.04. For example, [this commit](https://github.com/TAMS-Group/mecheye_ros_interface/commit/3007bd65723aef20598839bd5c9b35878e57fd2e) can make the CMake file work both in Ubuntu 18.04 and 20.04.
It might be a good idea to also make the CMake file work on ubuntu 16.04. So people do not need to rename the CMakelist file when compiling it.

**Comment by JS00000** [comment]
> I think there is no need to add a new file for ubuntu 20.04. For example, [this commit](https://github.com/TAMS-Group/mecheye_ros_interface/commit/3007bd65723aef20598839bd5c9b35878e57fd2e) can make the CMake file work both in Ubuntu 18.04 and 20.04.
> It might be a good idea to also make the CMake file work on ubuntu 16.04. So people do not need to rename the CMakelist file when compiling it.

Yes, it is a good idea. Now the CMakeLists_ubuntu18.txt can work on both ubuntu 18.04 and 20.04. But I do not have a ubuntu 16.04 environment now, so I cannot merge them all together.

**Comment by lianghongzhuo** [comment]
Thanks, looks good to me.

**Comment by lianghongzhuo** [comment]
This PR can be closed as the PR in https://github.com/MechMindRobotics/mecheye_ros_interface/pull/9 included the support of ubuntu 20.04.

**Pull request closed without merging**
